name: Stage Administrator CI/CD

on:
  push:
    branches:
      - stage
    paths:
      - 'projects/authorizer/**'

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
        aws-region: us-east-1
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run authstage

    - name: Deploy to S3
      if: success()
      run: aws s3 sync ./dist/authorizer/stage s3://stagevalepro-admin-authorizer

